@startuml

class Persona {
  +int id
  +str nombre
  +str apellido
  +float peso
  +float talla
  +datetime fecha_nacimiento
  +float medida_brazos
  +float medida_pecho
  +float medida_abdomen
  +float medida_cintura
  +float medida_piernas
}

class PersonaEntrenamiento {
  +int id_persona
  +int id_entrenamiento
  +datetime fecha_fin
  +datetime fecha_inicio
  +str razon_fin_entrenamiento
}

class Entrenamiento {
  +int id
  +datetime fecha
  +Ejercicio ejercicio
  +int repeticiones
}

class Ejercicio {
  +int id
  +str nombre
  +str descripcion
  +float calorias_por_repeticion
  +str enlace_youtube
}

Persona "1" -- "0..*" PersonaEntrenamiento : realiza
PersonaEntrenamiento "1" -- "1" Entrenamiento : realiza
Entrenamiento "1" *-- "0..*" Ejercicio : tiene

@enduml